# Generated by Django 3.0.7 on 2021-09-25 17:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie_tv', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tv',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='user_added_tv_in_favs_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tv',
            name='watch_list',
            field=models.ManyToManyField(blank=True, related_name='user_added_tv_in_watch_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tv',
            name='watched_list',
            field=models.ManyToManyField(blank=True, related_name='user_added_tv_in_watched_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movie',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='user_added_this_in_favs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movie',
            name='watch_list',
            field=models.ManyToManyField(blank=True, related_name='user_added_in_watch_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movie',
            name='watched_list',
            field=models.ManyToManyField(blank=True, related_name='user_added_in_watched_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
